# Generated by Django 5.0.6 on 2024-06-07 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.balance'),
        ),
        migrations.AlterField(
            model_name='apikeys',
            name='api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apikeys',
            name='api_secret',
            field=models.TextField(blank=True, null=True),
        ),
    ]
